server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: remittance-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

nexuspay:
  client:
    membership:
      base-url: ${MEMBERSHIP_BASE_URL:http://localhost:8081}
    money:
      base-url: ${MONEY_BASE_URL:http://localhost:8083}
    banking:
      base-url: ${BANKING_BASE_URL:http://localhost:8082}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
